---
- name: Get project {{ PROJECT_NAME }} info
  uri:
    url: "https://{{ harborURL }}/api/v2.0/projects/{{ PROJECT_NAME }}"
    method: GET
    user: "{{ harborUserName }}"
    password: "{{ harborPassword }}"
    force_basic_auth: yes
    validate_certs: false
    follow_redirects: all
  register: project_info

- name: Project {{ PROJECT_NAME }} is not content retention_id
  debug:
    msg: "harbor project {{ project_info.json.name }} is no retention_id"
  when: "'retention_id' not in project_info.json.metadata"

- name: Project {{ PROJECT_NAME }} is content retention_id
  debug:
    msg: "harbor project {{ project_info.json.name }} retention_id is {{ project_info.json.metadata.retention_id }}"
  when: project_info.json.metadata.retention_id is defined

- name: Trigger Project {{ PROJECT_NAME }} retention
  uri:
    url: "https://{{ harborURL }}/api/v2.0/retentions/{{ project_info.json.metadata.retention_id }}/executions"
    method: POST
    user: "{{ harborUserName }}"
    password: "{{ harborPassword }}"
    body: "{{ lookup('file','../files/api_trigger_project_retention.json') }}"
    body_format: json
    force_basic_auth: yes
    validate_certs: false
    follow_redirects: all
    status_code: 201
  when: "'retention_id' in project_info.json.metadata"
  register: retention_info_headers

- name: Show Project {{ PROJECT_NAME }} retention info
  debug:
    msg: "{{ retention_info_headers }}"
  when: "'retention_id' in project_info.json.metadata"

- name: Polling Project {{ PROJECT_NAME }} Retention Status
  uri:
    url: "{{ retention_info_headers.location }}/tasks"
    # url: "https://192.168.50.11/api/v2.0/retentions/13/executions/3831/tasks"
    method: GET
    user: "{{ harborUserName }}"
    password: "{{ harborPassword }}"
    force_basic_auth: yes
    validate_certs: false
    follow_redirects: all
  delay: "{{ IMAGE_RETENTINO_POLLING_DELAY }}"
  retries: "{{ IMAGE_RETENTINO_POLLING_RETRY }}"
  when: "'retention_id' in project_info.json.metadata"
  register: retention_polling_res
  until: "{{ retention_polling_res.json | selectattr('status', '!=', 'Success') | list | length == 0 }}"
# - name: debug Project {{ PROJECT_NAME }} test01
#   debug:
#     msg: "{{ retention_polling_res['json']  | selectattr('status', '!=', 'Success')  | list }}"
#   when: "'retention_id' in project_info.json.metadata"
