---
- name : Harbor Image House Keeping
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../vars/config.yaml

  tasks:
    - name: Trigger harbor projects retention
      include_tasks: harbor-retention.yaml
      loop: "{{ PROJECT_NAMES.split(',') }}"
      loop_control:
        loop_var: PROJECT_NAME

    - name: Trigger harbor gc
      uri:
        url: "https://{{ harborURL }}/api/v2.0/system/gc/schedule"
        method: POST
        user: "{{ harborUserName }}"
        password: "{{ harborPassword }}"
        body: "{{ lookup('file','../files/api_trigger_gc.json') }}"
        body_format: json
        force_basic_auth: yes
        validate_certs: false
        follow_redirects: all
        status_code: 201
