harborURL: 192.168.50.11
harborUserName: admin
harborPassword: admin12345
IMAGE_RETENTINO_POLLING_DELAY: 1
IMAGE_RETENTINO_POLLING_RETRY: 20
PROJECT_NAMES: 'seyana,openshift4-operator,openshift,openshift4'
